FROM rust:latest

# COPY <<EOF /etc/apt/sources.list
# deb http://mirrors.aliyun.com/debian bookworm main contrib non-free non-free-firmware
# deb http://mirrors.aliyun.com/debian bookworm-updates main contrib non-free non-free-firmware
# deb http://mirrors.aliyun.com/debian-security bookworm-security main contrib non-free non-free-firmware
# EOF
RUN sed -i 's|deb.debian.org/debian|mirrors.aliyun.com/debian|g' /etc/apt/sources.list.d/debian.sources && \
    apt-get update && apt-get -y upgrade && apt-get install -y --no-install-recommends \
    libclang-dev postgresql postgresql-contrib debian-keyring \
    debian-archive-keyring apt-transport-https \
    curl \
    && curl -1sLf 'https://dl.cloudsmith.io/public/caddy/testing/gpg.key' \
    | gpg --dearmor -o /usr/share/keyrings/caddy-testing-archive-keyring.gpg \
    && curl -1sLf 'https://dl.cloudsmith.io/public/caddy/testing/debian.deb.txt' \
    | tee /etc/apt/sources.list.d/caddy-testing.list \
    && apt-get update \
    && apt-get install -y caddy systemctl inetutils-ping libnss3-tools